## dashboard/dc/config/dc_labels.py

DC_LABEL_MAP = {
    "Id": "Drain Current Id (A)",
    "Ig": "Gate Current Ig (A)",
    "gm": "Transconductance gm (S)",
    "gds": "Output Conductance gds (S)",
    "Cgs": "Gate-Source Capacitance Cgs (F)",
    "Cgd": "Gate-Drain Capacitance Cgd (F)",
    "Cgg": "Gate Capacitance Cgg (F)",
    "Ft_mean": "Ft Mean (GHz)",
    "Ft": "Ft (GHz)",
    "Fmax": "Fmax (GHz)",
    "Fmax_mean": "Fmax Mean (GHz)",
    "h21_mag": "Current gain |h21|",
    "h21_dB": "Current gain h21(dB)",
    "S11_dB": "S11 (dB)",
    "S12_dB": "S12 (dB)",
    "S21_dB": "S21 (dB)",
    "S22_dB": "S22 (dB)",
    "S11": "S11",
    "S12": "S12",
    "S21": "S21",
    "S22": "S22",
    "Y11_dB": "Y11 (dB)",
    "Y12_dB": "Y12 (dB)",
    "Y21_dB": "Y21 (dB)",
    "Y22_dB": "Y22 (dB)",
    "Y11_mag": "Y11",
    "Y12_mag": "Y12",
    "Y21_mag": "Y21",
    "Y22_mag": "Y22",
}
